<meta charset="UTF-8">

<link rel="icon" href="././assets/images/favicon.png" type="image/png" />

<meta name="viewport" content="width=device-width, initial-scale=1.0">

<link rel="stylesheet" href="./style/main.css">
<link rel="stylesheet" href="./style/menu_mobile.css">

<script src="././assets/libs/jquery-3.6.0.min.js"></script>
<script src="././assets/libs/md5.js"></script>
<script src="././js/main.js"></script>