<div class="modal fade " id="excluirConta" tabindex="-1" role="dialog" aria-labelledby="important-msg-label" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
        <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
            <h4 class="modal-title">Excluir Conta</h4>
        </div>
        <div class="modal-body">
            <p class="modal-text">Tem certeza que deseja excluir sua conta?</p>
        </div>
        <div class="modal-footer">
            <button class="data-user-action-cancel" data-dismiss="modal">Não</button>
            <button class="data-user-action-save remover">Sim</button>
        </div>
        </div>
    </div>
</div>