<div class="modal fade " id="alterarDados" tabindex="-1" role="dialog" aria-labelledby="important-msg-label" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
        <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
            <h4 class="modal-title">Alterar Dados</h4>
        </div>
        <div class="modal-body modal-form">
            <input type="text" name="nome" placeholder="Nome Completo" />
            <input type="text" name="nome" placeholder="Nome Completo" />
            <input type="text" name="nome" placeholder="Nome Completo" />
        </div>
        <div class="modal-footer">
            <button class="data-user-action-cancel" data-dismiss="modal">Cancelar</button>
            <button class="data-user-action-save">Salvar</button>
        </div>
        </div>
    </div>
</div>