<div class="modal fade " id="areaDescricao" tabindex="-1" role="dialog" aria-labelledby="important-msg-label" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
          <div class="modal-header">
              <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
              <h2 class="modal-title"></h2>
          </div>
          <div class="modal-body">
              <div id="descricao"></div>
          </div>
        </div>
    </div> 
</div> 